name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  dev-merge:
    name: Build, Test, and Merge on dev branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Install dependencies (backend & frontend)
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Run unit tests (backend & frontend)
        run: |
          cd backend
          npm test
          cd ../frontend
          npm test

      - name: Merge dev into main (if tests pass)
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout main
          git merge dev
          git push origin main

  main-deploy:
    name: Build, Test, and Deploy on main branch
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Install dependencies (backend & frontend)
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      - name: Run unit tests (backend & frontend)
        run: |
          cd backend
          npm test
          cd ../frontend
          npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push