name: Feature to Dev Workflow

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  feature-to-dev-workflow:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install dependencies
        run: |
          npm install

      - name: Run unit tests
        run: |
          npm test


      - name: Proceed if unit tests pass
        if: success()
        run: echo "Unit tests passed. Proceeding to merge with main."


      - name: Merge Dev into Main
        if: success()
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
