name: Dev Workflow

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  feature-to-dev-workflow:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install dependencies for backend
        run: |
          cd backend
          npm install


      - name: Run unit tests for backend
        run: |
          cd backend
          npm test


      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install


      - name: Run unit tests for frontend
        run: |
          cd frontend
          npm test


      - name: Proceed if unit tests pass
        if: success()
        run: echo "Unit tests passed. Proceeding to merge with main."


      - name: Merge Dev into Main
        if: success()
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
