name: Main Workflow

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  main-workflow:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install dependencies for backend
        run: |
          cd backend
          npm install


      - name: Run unit tests for backend
        run: |
          cd backend
          npm test


      - name: Install dependencies for frontend
        run: |
          cd frontend
          npm install

      - name: Run unit tests for frontend
        run: |
          cd frontend
          npm test


      - name: Login to Docker Hub
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"username": "${{ secrets.DOCKER_USERNAME }}", "password": "${{ secrets.DOCKER_PASSWORD }}"}' https://hub.docker.com/v2/users/login/ > login_response.json
          export DOCKER_HUB_TOKEN=$(cat login_response.json | jq -r .token)

      - name: Create Docker Hub repository
        run: |
          curl -X POST https://hub.docker.com/v2/repositories/ \
            -H "Authorization: Bearer $DOCKER_HUB_TOKEN" \
            -d '{
              "name": "your-repository-name",
              "description": "This is a new repository created from GitHub Actions",
              "is_private": false
            }'
